### PR TITLE
Fix compilation on OS X (at least 10.9)

### PR DESCRIPTION
**Pull request by NikolausDemmel**
- without this patch the build fails because this symbol is not defined in
  termios.h

### CODE REVIEW

**Comment by stonier** [comment]
This would only fix for one baud rate right? Almost should have a mac only header that sets these for all of the baud rate symbols we use.

**Comment by NikolausDemmel** [comment]
At least on OS X 10.9, where I compiled this, this one baud rate is the only one missing from termios.h

Not sure if there is some (POSIX?) standard for which baud rates should be defined in termios.h. Maybe 921600, which seems to be included on Linux, is beyond the standard. I know too little about this stuff.

**Comment by stonier** [comment]
Ah, looks like B921600 is not actually posix - http://digilander.libero.it/robang/rubrica/serial.htm#3_1_1 but has been around on linux/freebsd for some years now.

I'll merge this a little later when I can add a comment about this with the pull request.

**Comment by NikolausDemmel** [comment]
That makes sense. Thanks for looking into it.

**Comment by stonier** [comment]
Those two commits push into hydro-devel and indigo respectively.

**Pull request closed without merging**
