### PR TITLE
export include directories

### PR DESCRIPTION
**Pull request by Karsten1987**
We need this changes in order for colcon to correctly build the turtlebot packages correctly. 
AFAIK, `ament_target_dependencies` does not work with interfaces and there the packages need to explicitly export their include directories.

### CODE REVIEW

**Comment by stonier** [comment]
Hmm, seems `ament_target_dependencies` is new and it also looks like a rethink on their usual desire to stay as close as possible to the build system as possible (ROS build commands used to be wrapped in these kind of wrappers, with catkin they deliberately went away from it).

Regardless of my preference, I wonder if we can get `ament_target_dependencies` patched to make use of the include directory information that is already inside the exported interfaces rather than proliferating redundant information. Let me investigate that with them before accepting this PR.

**Comment by stonier** [comment]
Sending PR upstream: https://github.com/ament/ament_cmake/pull/178

**Comment by Karsten1987** [comment]
I added a few more commits to this branch to allow a compilation with `-Werror` and `-Wpedantic`. Plus, I had to change the way `c++14` is enabled for Apple devices in order to build the tests correctly.

**Comment by stonier** [comment]
With respect to the exported includes....

Given that the upstream patch has run into complications, I can do one of either two things here: 

1. Swing both ways, i.e. duplicate exports for include directories/libraries, ... and interfaces
2. Leave as is, and just recommend others to add ecl dependencies via, e.g. `target_link_libraries(mytarget ecl_time::ecl_time)`...i.e. cmake style

@Karsten1987 was it `kobuki_core` that you were needing the ecl dependencies for?

**Comment by Karsten1987** [comment]
Correct, I stumbled upon `ecl` in order to get the `kobuki_core` packages to run successfully. 

I am okay with modifying the `kobuki_core` packages accordingly to use an explicit `target_link_libraries` until your referenced patch in `ament_cmake` in resolved.

**Comment by stonier** [comment]
Took the pedantic fixes and corrected it so it builds correctly on linux as well. Merged in PR #89, releasing as 1.0.3.

As with https://github.com/stonier/ecl_lite/pull/30, not applying the export includes, kobuki_core will make direct use of target_link_libraries once we get there.

**Pull request closed without merging**
